---
abstract: 'Copy (or move) specific files after building (for SCM inclusion, etc.)'
author:
  - 'Ryan C. Thompson <rct@thompsonclan.org>'
build_requires:
  Carp: 0
  File::Spec: 0
  IO::Handle: 0
  IPC::Open3: 0
  Scalar::Util: 0
  Test::More: 0.94
  perl: 5.008
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.132661'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-CopyFilesFromBuild
no_index:
  directory:
    - corpus
requires:
  Dist::Zilla::Role::AfterBuild: 0
  File::Copy: 0
  List::AllUtils: 0
  Moose: 0
  Moose::Autobox: 0
  MooseX::Has::Sugar: 0
  Set::Scalar: 0
  perl: 5.008
  strict: 0
  utf8: 0
  warnings: 0
resources:
  homepage: https://github.com/DarwinAwardWinner/Dist-Zilla-Plugin-CopyFilesFromBuild
  repository: https://github.com/DarwinAwardWinner/Dist-Zilla-Plugin-CopyFilesFromBuild.git
version: 0.142220
